services:
  - type: web
    name: boocs-messenger-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ACCESS_SECRET
        generateValue: true
      - key: REFRESH_SECRET
        generateValue: true
