services:
  - type: web
    name: boocs-messenger-api
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ACCESS_SECRET
        generateValue: true
      - key: REFRESH_SECRET
        generateValue: true
